name: snyk-labs/action example - Snyk SCM Issues to Github Issues
on: [push]
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: snyk-labs/actions/snyk-scm-issues-to-gh-issues@feat/options-for-scm-issues-to-gh-issues
        with:
          options: --use-fresh-issues
          snyk_prefix: "cse"
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          GITHUB_TOKEN: ${{ github.token }}
          REMOTE_REPO_URL: ${{ github.repositoryUrl }}
