name: Snyk SCM Issues to Github Issues (nightly)
on:
  schedule:
    - cron: '0 4 * * *' # run at 4:00 AM UTC
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: snyk-labs/actions/snyk-scm-issues-to-gh-issues@main
        with:
          snyk_prefix: "cse"
          use_fresh_issues: "true"
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          GITHUB_TOKEN: ${{ github.token }}
          REMOTE_REPO_URL: ${{ github.repositoryUrl }}
