name: snyk-labs/action example - Snyk SCM Issues to Github Issues
on: 
  push:
    branches:
      - master
      - main
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: snyk-labs/actions/snyk-scm-issues-to-gh-issues@feat/use-fresh-issues-option
        with:
          snyk_prefix: "cse"
          use_fresh_issues: "true"
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          GITHUB_TOKEN: ${{ github.token }}
          REMOTE_REPO_URL: ${{ github.repositoryUrl }}
